---
title: DSC 530 Week 5 & 6 Coding Assignment
---

## Assignment

This week’s exercise offers you the flexibility to choose which Python modules or packages you want to use for the coding tasks. You can refer to the textbook solution file to verify if your calculated outputs are correct. Keep in mind that different functions may yield slightly different values due to variations in algorithms. Precision and rounding are handled differently by specific packages and functions. Understanding the specific method applied is an important part of making informed decisions when interpreting results.

This assignment is a great opportunity for you to explore various functions for summary statistics and plotting. You will not be penalized as long as your documentation clearly justifies and explains the functions you choose to use for each task.

- [x] Setup your assignment notebook with access to the Chapter 4 data files from Hands-on data analysis with Pandas (Molin, 2021) and use Jupyter Lab/Notebook to complete the following problems:

- [x] Exercises 1, 2, 4, 6, 7, and 10 from Chapter 4 in Hands-On Data Analysis with Pandas (Molin, 2021). These exercises can also be found in Chapter 4 in the Molin textbook. Using the CSV file in the exercises/ folder and what we have learned so far in this book, complete the following exercises:

## Submission Instructions:

Use Jupyter Lab or Jupyter Notebook to complete all the exercise problems and submit your code solutions with clearly displayed code outputs in one ipynb file.
You may convert your ipynb file as a PDF file for submission, but this is not required. If you want to make your work available in PDF format, you will have to install the necessary Python packages to do that. Other methods, such as print screens or print to PDF often produce a distorted image of your Jupyter Notebook and if the instructor cannot clearly see your solutions and outputs, your work will be rejected.
You must show all your code and the successfully produced outputs along with documentation to be considered for full credit. 
The assignment is due by Sunday of Week 6, 11:59 p.m. CT.

## Checklist

**Hands-On Data Analysis using Pandas** (Chapter 4)

- [x] Exercise 1
- [x] Exercise 2
- [x] Exercise 4
- [x] Exercise 6
- [x] Exercise 7
- [x] Exercise 10

## Exercise 1.

With the earthquakes.csv file, select all the earthquakes in Japan with a magnitude of 4.9 or greater using the mb magnitude type.

In [14]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/chapter_4/earthquakes.csv')
mb = df[df['magType'] == 'mb' ] # select magType = mb
mag = mb[mb['mag'] >= 4.9 ] # select earthquakes with mag >= 4.9
japan = mag[mag['parsed_place'] == 'Japan' ] # select parsed place Japan
japan.head()

,mag,magType,time,place,tsunami,parsed_place
1563,4.9,mb,1538977532250,"293km ESE of Iwo Jima, Japan",0,Japan
2576,5.4,mb,1538697528010,"37km E of Tomakomai, Japan",0,Japan
3072,4.9,mb,1538579732490,"15km ENE of Hasaki, Japan",0,Japan
3632,4.9,mb,1538450871260,"53km ESE of Hitachi, Japan",0,Japan

## Exercise 2.

Create bins for each full number of earthquake magnitude (for instance, the first bin is (0,1], the second is (1,2], and so on) with the ml magnitude type and count how many are in each bin.

In [27]:
df = pd.read_csv('data/chapter_4/earthquakes.csv')
ml = df[df['magType'] == 'ml']
mag = ml['mag']
bins = [0, 1, 2, 3, 4, 5, 6]
mag_binned = pd.cut(
    mag, bins = bins)
mag_binned.value_counts()

mag
(1, 2]    3105
(0, 1]    2207
(2, 3]     862
(3, 4]     122
(4, 5]       2
(5, 6]       1
Name: count, dtype: int64

## Exercise 4.

Build a crosstab with the earthquake data between the tsunami column and the magType column. Rather than showing the frequency count, show the maximum magnitude that was observed for each combination. Put the magnitude type along the columns.

In [50]:
df.head()
pd.crosstab(
    index = df.magType,
    columns = df.tsunami,
    values = df.mag,
    aggfunc = 'max'
)

tsunami     0     1
magType
mb       5.60  6.10
mb_lg    3.50   NaN
md       4.11   NaN
mh       1.10   NaN
ml       4.20  5.10
ms_20     NaN  5.70
mw       3.83  4.41
mwb      5.80   NaN
mwr      4.80   NaN
mww      6.00  7.50

## Exercise 6.

Create a pivot table of the FAANG data that compares the stocks. Put the ticker in the rows and show the averages of the OHLC and volume traded data.

In [96]:
import pandas as pd
faang = pd.read_csv('data/chapter_4/faang.csv')
faang.head()
pd.pivot_table(
    faang,
    values=['open', 'high', 'low', 'close', 'volume'],
    index='ticker',
    aggfunc='mean'
)

              close         high          low         open        volume
ticker
AAPL     186.986218   188.906858   185.135729   187.038674  3.402145e+07
AMZN    1641.726175  1662.839801  1619.840398  1644.072669  5.649563e+06
FB       171.510936   173.615298   169.303110   171.454424  2.768798e+07
GOOG    1113.225139  1125.777649  1101.001594  1113.554104  1.742645e+06
NFLX     319.290299   325.224583   313.187273   319.620533  1.147030e+07

## Exercise 7.

Calculate the z-scores for each numeric column of Amazon’s data (ticker is AMZN) in Q4 2018 using apply().

In [167]:
faang.head()
amzn = faang[faang['ticker']=='AMZN']
q4 = amzn[amzn['date'].between('2018-10-01', '2018-12-31')]
q4_arr = np.array([q4.open, q4.high, q4.low, q4.close, q4.volume]).flatten()
def zscore(array):
    zscore = (array - np.mean(array))/np.std(array)
    return zscore

q4_df = pd.DataFrame([q4.open, q4.high, q4.low, q4.close, q4.volume])
zscore_df = q4_df.apply(zscore)
print(zscore_df)

             690       691       692       693       694       695       696  \
open   -0.499996 -0.499994 -0.499994 -0.499993 -0.499993 -0.499998 -0.500005
high   -0.499987 -0.499988 -0.499990 -0.499990 -0.499989 -0.499988 -0.499986
low    -0.500009 -0.500010 -0.500009 -0.500011 -0.500014 -0.500013 -0.500009
close  -0.500008 -0.500008 -0.500007 -0.500006 -0.500004 -0.500001 -0.500000
volume  2.000000  2.000000  2.000000  2.000000  2.000000  2.000000  2.000000

             697       698       699  ...       743       744       745  \
open   -0.499988 -0.499999 -0.499994  ... -0.499993 -0.500002 -0.499995
high   -0.499988 -0.499994 -0.499994  ... -0.499990 -0.499992 -0.499983
low    -0.500012 -0.500006 -0.500012  ... -0.500010 -0.500009 -0.500012
close  -0.500012 -0.500000 -0.500000  ... -0.500006 -0.499998 -0.500009
volume  2.000000  2.000000  2.000000  ...  2.000000  2.000000  2.000000

             746       747       748       749       750       751       752
open   -0.499997 -0.499992 -0.500001 -0.500012 -0.499997 -0.500001 -0.499998
high   -0.499991 -0.499989 -0.499983 -0.499987 -0.499994 -0.499990 -0.499994
low    -0.500010 -0.500011 -0.500014 -0.500013 -0.500014 -0.500008 -0.500007
close  -0.500003 -0.500008 -0.500001 -0.499988 -0.499995 -0.500000 -0.500001
volume  2.000000  2.000000  2.000000  2.000000  2.000000  2.000000  2.000000

[5 rows x 63 columns]

In [136]:
faang.head()
amzn.head()
q4.head()

    ticker        date     open     high      low    close   volume
690   AMZN  2018-10-01  2021.99  2033.19  2003.60  2004.36  3468285
691   AMZN  2018-10-02  1999.99  2013.39  1965.77  1971.31  5400749
692   AMZN  2018-10-03  1981.70  1989.70  1949.81  1952.76  5253131
693   AMZN  2018-10-04  1949.00  1956.00  1896.57  1909.42  7256973
694   AMZN  2018-10-05  1917.99  1929.08  1862.83  1889.65  6822327

## Exercise 10.

The European Centre for Disease Prevention and Control (ECDC) provides an open dataset on COVID-19 cases called daily number of new reported cases of COVID-19 by country worldwide. This dataset is updated daily, but we will use a snapshot that contains data through September 18, 2020. Complete the following tasks to practice the skills you've learned up to this point in the book:

- [x] Prepare the data
- [x] Read in the data in the covid19_cases.csv file.
- [x] Create a date column by parsing the dateRep column into a datetime.
- [x] Set the date column as the index.
- [x] Use the replace() method to update all occurrences of United_States_of_America and United_Kingdom to USA and UK, respectively.
- [x] Sort the index.
- [x] For the five countries with the most cases (cumulative), find the day with the largest number of cases.
- [x] Find the 7-day average change in COVID-19 cases for the last week in the data for the five countries with the most cases.
- [x] Find the first date that each country other than China had cases.
- [x] Rank the countries by cumulative cases using percentiles.

In [297]:
# prepare and read the data in the covid19_cases.csv file
covid = pd.read_csv('data/chapter_4/covid19_cases.csv')
df = pd.DataFrame(covid)

# create a date column by parsing the dateRep column into a datetime.
# sort the index
df['dateRep'] = pd.to_datetime(df['dateRep'], format = '%d/%m/%Y')
df['date'] = df['dateRep']
df = df.set_index('dateRep').sort_index()

# use the replace() method to update all occurrences of United_States_of_America and United_Kingdom to USA and UK, respectively.
df.replace('United_States_of_America','USA')
df.replace('United_Kingdom','UK')

# for the five countries with the most cases (cumulative), find the day with the largest number of cases.
top_5 = ['Netherlands','Spain','Italy','Germany','France']
df_5 = df[df['countriesAndTerritories'].isin(countries)]
max_df_5 = df_5.loc[df_5.groupby('countriesAndTerritories').cases.idxmax().sort_values(),['date','countriesAndTerritories','cases']]
max_df_5 = max_df_5.set_index('cases').sort_index(ascending = False)
# Netherlands = 2022-02-08	
# Spain = 2022-01-10
# Italy = 2022-01-18	
# Germany = 2022-03-23
# France = 2022-01-25

# find the 7-day average change in COVID-19 cases for the last week in the data for the five countries with the most cases.
df['7day_avg'] = (
    df.groupby('countriesAndTerritories')['cases']
    .transform(lambda x: x.rolling(7).mean())
)

# find the first date that each country other than China had cases.
last_date = df.index.max()
last_week = df.loc[last_date - pd.Timedelta(days=6): last_date]
last_week_top5 = last_week[last_week['countriesAndTerritories'].isin(top_5)]

# rank the countries by cumulative cases using percentiles.
avg_change_last_week = (
    last_week_top5.groupby('countriesAndTerritories')['cases'].mean().sort_values(ascending=False)
)
avg_change_last_week

countriesAndTerritories
Germany        48197.6
France         37600.6
Italy          29121.4
Spain          25422.0
Netherlands     1818.0
Name: cases, dtype: float64

In [227]:
df.hea

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2020,continentExp
0,2022-10-23,23,10,2022,3557.0,0.0,Austria,AT,AUT,8901064,Europe
1,2022-10-22,22,10,2022,5494.0,4.0,Austria,AT,AUT,8901064,Europe
2,2022-10-21,21,10,2022,7776.0,4.0,Austria,AT,AUT,8901064,Europe
3,2022-10-20,20,10,2022,8221.0,6.0,Austria,AT,AUT,8901064,Europe
4,2022-10-19,19,10,2022,10007.0,8.0,Austria,AT,AUT,8901064,Europe