- DSC 530 Data Exploration and Analysis
- DSC 530 Weeks 1 & 2 Coding Assignment
- Dong Woon Kim

In [2]:
# Import modules
import pandas as pd
import numpy as np

# Chapter 3

## Exercise 1

We want to look at data for the Facebook, Apple, Amazon, Netflix, and Google (FAANG) stocks, but we were given each as a separate CSV file (obtained using the stock_analysis package we will build in Chapter 7, Financial Analysis – Bitcoin and the Stock Market). Combine them into a single file and store the dataframe of the FAANG data as faang for the rest of the exercises:

Read in the aapl.csv, amzn.csv, fb.csv, goog.csv, and nflx.csv files.
Add a column to each dataframe, called ticker, indicating the ticker symbol it is for (Apple's is AAPL, for example); this is how you look up a stock. In this case, the filenames happen to be the ticker symbols.
Append them together into a single dataframe.
Save the result in a CSV file called faang.csv

In [11]:
# Import datasets from CSV files
netflix = pd.read_csv("data/nflx.csv")
apple = pd.read_csv("data/aapl.csv")
amazon = pd.read_csv("data/amzn.csv")
facebook = pd.read_csv("data/fb.csv")
google = pd.read_csv("data/goog.csv")

# Add 'ticker' column
netflix['ticker'] = 'NFLX'
apple['ticker'] = 'AAPL'
amazon['ticker'] = 'AMZN'
facebook['ticker'] = 'META'
google['ticker'] = 'GOOG'

# Append the df's together
faang = pd.concat([netflix, apple, amazon, facebook, google])

# Save the result in a CSV file called faang.csv
faang.to_csv('data/faang.csv')

## Exercise 2

With faang, use type conversion to cast the values of the date column into datetimes and the volume column into integers. Then, sort by date and ticker.

In [25]:
pd.to_datetime(faang['date'])
faang['volume'].astype(int)
faang.info()
faang.sort_values('ticker')
faang.sort_values('date')

<class 'pandas.core.frame.DataFrame'>
Index: 1255 entries, 0 to 250
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1255 non-null   object
 1   open    1255 non-null   float64
 2   high    1255 non-null   float64
 3   low     1255 non-null   float64
 4   close   1255 non-null   float64
 5   volume  1255 non-null   int64
 6   ticker  1255 non-null   object
dtypes: float64(4), int64(1), object(2)
memory usage: 78.4+ KB

           date       open       high        low      close    volume ticker
0    2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX
0    2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0    2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903   META
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
0    2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
..          ...        ...        ...        ...        ...       ...    ...
250  2018-12-31  1510.8000  1520.7600  1487.0000  1501.9700   6954507   AMZN
250  2018-12-31   260.1600   270.1001   260.0000   267.6600  13508920   NFLX
250  2018-12-31   134.4500   134.6400   129.9500   131.0900  24625308   META
250  2018-12-31   157.8529   158.6794   155.8117   157.0663  35003466   AAPL
250  2018-12-31  1050.9600  1052.7000  1023.5900  1035.6100   1493722   GOOG

[1255 rows x 7 columns]

## Exercise 3

In [33]:
faang.sort_values('volume', ascending = False)
faang.tail(7)

           date     open     high      low    close   volume ticker
244  2018-12-20  1018.13  1034.22   996.36  1009.41  2673464   GOOG
245  2018-12-21  1015.30  1024.02   973.69   979.54  4595891   GOOG
246  2018-12-24   973.90  1003.54   970.11   976.22  1590328   GOOG
247  2018-12-26   989.01  1040.00   983.00  1039.46  2373270   GOOG
248  2018-12-27  1017.15  1043.89   997.00  1043.88  2109777   GOOG
249  2018-12-28  1049.62  1055.56  1033.10  1037.08  1413772   GOOG
250  2018-12-31  1050.96  1052.70  1023.59  1035.61  1493722   GOOG

# Exercise 4

Right now, the data is somewhere between long and wide format. Use melt() to make it completely long format. Hint: date and ticker are our ID variables (they uniquely identify each row). We need to melt the rest so that we don't have separate columns for open, high, low, close, and volume.

In [34]:
pd.melt(faang)

     variable       value
0        date  2018-01-02
1        date  2018-01-03
2        date  2018-01-04
3        date  2018-01-05
4        date  2018-01-08
...       ...         ...
8780   ticker        GOOG
8781   ticker        GOOG
8782   ticker        GOOG
8783   ticker        GOOG
8784   ticker        GOOG

[8785 rows x 2 columns]

# Exercise 5

Suppose we found out that on July 26, 2018 there was a glitch in how the data was recorded. How should we handle this? Note that there is no coding required for this exercise.

There are multiple ways to handle invalid data, the most common of which is to drop the value from the column. Another method is to drop the entire column, replace the value with a running average or estimation of the potential "true" value. 

In this particular case, with only one invalid value within a column, I would remove this value only.

# Exercise 6

The European Centre for Disease Prevention and Control (ECDC) provides an open dataset on COVID-19 cases called daily number of new reported cases of COVID-19 by country worldwide. This dataset is updated daily, but we will use a snapshot that contains data from January 1, 2020 through September 18, 2020. Clean and pivot the data so that it is in wide format:



- [x] Read in the covid19_cases.csv file.
- [x] Create a date column using the data in the dateRep column and the pd.to_datetime() function.
- [x] Set the date column as the index and sort the index.
- [x] Replace all occurrences of United_States_of_America and United_Kingdom with USA and UK, respectively. Hint: the replace() method can be run on the dataframe as a whole.
- [x] Using the *countriesAndTerritories* column, filter the cleaned COVID-19 cases data down to Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA.
- [x] Pivot the data so that the index contains the dates, the columns contain the country names, and the values are the case counts (the cases column). Be sure to fill in NaN values with 0.

In [151]:
# 1. Prepare and read the data in the covid19_cases.csv file
df = pd.read_csv('data/covid19.csv')
df = pd.DataFrame(df)

# 2. Create a date column

df['dateRep'] = pd.to_datetime(df['dateRep'], format = '%d/%m/%Y')

# 3. Set the date column as the index and sort the index
df = df.set_index('dateRep').sort_index()

# 4. Use the replace() method to update all occurrences of United_States_of_America and United_Kingdom to USA and UK, respectively.

df.replace('United_States_of_America','USA')
df.replace('United_Kingdom','UK')

# 5. Using the countriesAndTerritories column, filter the cleaned COVID-19 cases data down to Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA.

countries = ['Argentina', 'Brazil', 'China', 'Colombia', 'India', 'Italy', 'Mexico', 'Peru', 'Russia', 'Spain', 'Turkey', 'USA', 'UK']
df = df[df['countriesAndTerritories'].isin(countries)]
df['countriesAndTerritories'].nunique()

# 6. Pivot the data so that the index contains the dates, the columns contain the country names, and the values are the case counts (the cases column). Be sure to fill in NaN values with 0.

df = pd.pivot_table(
    df,
    index = 'dateRep',
    columns = 'countriesAndTerritories', 
    values = 'cases',
    aggfunc = 'sum',
    fill_value = 0
)

df.head()

countriesAndTerritories,Argentina,Brazil,China,Colombia,India,Italy,Mexico,Peru,Russia,Spain,Turkey
dateRep,,,,,,,,,,,
2019-12-31,0,0,27,0,0,0,0,0,0,0,0
2020-01-01,0,0,0,0,0,0,0,0,0,0,0
2020-01-02,0,0,0,0,0,0,0,0,0,0,0
2020-01-03,0,0,17,0,0,0,0,0,0,0,0
2020-01-04,0,0,0,0,0,0,0,0,0,0,0